apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: moodle-pvc
  name: moodle-pvc
spec:
  storageClassName: nfs-client
  # storageClassName: premium-ssd1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
status: {}
