apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: moodle
  name: moodle
spec:
  replicas: 2
  serviceName: moodle-service
  selector:
    matchLabels:
      app: moodle
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: moodle
    spec:
      containers:
        - env:
          - name: DB_HOST
            value: 45.124.94.128
          - name: DB_NAME
            value: moodle
          - name: DB_USER
            value: duy
          - name: DB_PASS
            value: 4Yk7741J2JVWPTQkT9eKkcbAaTUs5XzTvIFL
          - name: REDIS_HOST
            value: 103.107.183.77
          - name: REDIS_PORT
            value: '6379'
          - name: REDIS_PASS
            value: Vcc123**
          - name: REDIS_LOCK_TIMEOUT
            value: '120'
          - name: REDIS_LOCK_EXPIRE
            value: '7200'
          - name: REDIS_LOCK_RETRY
            value: '100'
          image: cr-hn-1.bizflycloud.vn/c579f3ab86094f2c97f36b0877ead59a/moodle:testenv
          name: moodle
          resources:
            limits:
              cpu: "2000m"
              memory: "2Gi"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/moodledata
              name: moodle-pvc
      initContainers:
        - name: moodle-hack
          image: cr-hn-1.bizflycloud.vn/c579f3ab86094f2c97f36b0877ead59a/moodle:testenv
          command: ["/bin/sh", "-c"]
          args: ["rm -rf /var/www/moodledata/* && cp -rf  /var/www/moodledata_src/* /var/www/moodledata &&  chown -R 33:33 /var/www/moodledata"]
          volumeMounts:
          - name: moodle-pvc
            mountPath: /var/www/moodledata
      restartPolicy: Always
      volumes:
        - name: moodle-pvc
          persistentVolumeClaim:
            claimName: moodle-pvc
