// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "paths": {
		"/api/v1/packages": {
			"get": {
				"tags": ["Packages"],
				"summary": "Get all packages",
				"parameters": [
					{"in": "header", "name": "X-Auth-Token", "type": "string", "required": true},
					{"in": "header", "name": "X-Tenant-Name", "type": "string", "required": true},
					{"in", "query", "name": "page", "type": "integer", "format": "int64", "required": false},
					{"in", "query", "name": "limit", "type": "integer", "format": "int64", "required": false}
				],
				"produces": ["application/json"],
				"responses": {
					"200": {
						"description": "Get all packages",
						"schema": {
							"$ref": ""
						}
					}
				}
			}
		}
	}
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
