apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moodle
spec:
  ingressClassName: nginx
  rules:
    - host: test99.lms.bizflycloud.vn
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: moodle-service
                port:
                  number: 80
            path: /

