apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: moodle
  name: moodle
spec:
  replicas: 3
  serviceName: moodle-service
  selector:
    matchLabels:
      app: moodle
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: moodle
    spec:
      containers:
        - env:
          image: cr-hn-1.bizflycloud.vn/c579f3ab86094f2c97f36b0877ead59a/moodle:custom
          name: moodle
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/moodledata
              name: moodle-pvc
      initContainers:
        - name: moodle-hack
          image: cr-hn-1.bizflycloud.vn/c579f3ab86094f2c97f36b0877ead59a/moodle:custom
          command: ["/bin/sh", "-c"]
          args: ["rm -rf /var/www/moodledata/* && cp -rf  /var/www/moodledata_src/* /var/www/moodledata &&  chown -R 33:33 /var/www/moodledata"]
          volumeMounts:
          - name: moodle-pvc
            mountPath: /var/www/moodledata
      restartPolicy: Always
      volumes:
        - name: moodle-pvc
          persistentVolumeClaim:
            claimName: moodle-pvc
